version: 2
updates:
  # Maintain dependencies for yarn
  - package-ecosystem: "npm"
    directory: "/App"
    schedule:
      interval: "daily"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"